config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'lobbies#index'

  resources :students
  resources :games
  resources :teams

  resources :lobbies do
    collection do
      post :inlobby
      post :ingame
    end
  end

  resources :teachers do
    collection do
      post :increategame
      post :increatelobby
    end
  end

  # activate actioncable
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :lobbies
	has_many :teams
	# has_many :students, through: :teams
	# has_many :teachers, through: :lobby
end

app/models/link.rb
class Link < ActiveRecord::Base
	has_many :questions
  
end

app/models/lobby.rb
class Lobby < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :game
	has_many :students
	has_many :teams
end

app/models/question.rb
class Question < ActiveRecord::Base

end

app/models/student.rb
class Student <  ActiveRecord::Base

  belongs_to :teacher, optional: true
  belongs_to :lobby, optional: true
	belongs_to :team, optional: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :students
	has_many :lobbies
	has_many :games, through: :lobbies
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :students
	belongs_to :game
	belongs_to :lobby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
		@game = Game.find(1)
	end
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController

	before_action :authenticate_student!

	def index
		@lobby = Lobby.find(1)

		# reset lobby ID of current_student
		current_student.lobby_id = 0
		current_student.save
		Student.where(id: current_student.id).update_all(team_id: 0) 								# update team id to 0
    Student.where(id: current_student.id).update_all(player_number: 0)					# update player_number to 0
		Student.where(id: current_student.id).update_all(game_id: 0)								# update game_id to 0
		Student.where(id: current_student.id).update_all(progress: 0)								# update progress to 0
	end

	def inlobby
		# set student lobby_id to lobby_id of clicked lobby

		current_student.lobby_id = params[:lobby_id]
		Student.where(id: current_student.id).update_all(lobby_id: params[:lobby_id])

		# load the game that the lobby was set to have by the teacher
		@game_to_play = Game.find(Lobby.find(params[:lobby_id]).game_id)
		Student.where(id: current_student.id).update_all(game_id: @game_to_play.id)
	end

	def ingame

		# @qs = '{"names":["Africa","America", "Asia", "Australia"],"street":"Oslo West 16","phone":"555 1234567"}'
		# @qsj = JSON.parse(@qs)
		# @qsjl = @qsj.length
		# initialize everything
		@game_to_play = params[:game]
		@series = 1

	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_action :authenticate_student!, only: [:index]

	def index
		@student = Student.find(1)
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teacher = Teacher.find(1)
	end

	def increategame
		@questions = Question.order('id ASC')
	end

	def increatelobby
		@xx = "up tomorrow, it's a rainy day"
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@team = Team.find(1)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1> Game: <%= @game.as_json %> </h1>
<h6> Teams playing the game: </h6> <%= @game.teams.as_json %>
<h6> Students in the teams playing the game: </h6><%= @game.students.as_json %>
<h6> Lobby where game is being played </h6><%= @game.lobbies.as_json %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thesis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= yield :stylesheetsandscripts %>
  <%= csrf_meta_tags %>
</head>
<!--<body onload="playOpeningTheme()">-->
<body background="/imggrids/bg.jpg" class="booty">
  <h1></h1>
<table width="70%" align="center">
  <tr>
    <td>
      <% if student_signed_in? then %>
        <font class="cute-p"> Hello there, <%= current_student.first_name %> </font><br/>
        <!-- required by devise -->
        <p class="notice cute-p"><%= notice %></p>
      <% end %>
    </td>
    <td align="right" vertical-align="top">
      <%= link_to "Sign_up", new_student_registration_path, {:method => :get, class: "cute-p"} %>
      <%= link_to "Sign_in", new_student_session_path, {:method => :get, class: "cute-p"} %>
      <%= link_to "Sign_out", destroy_student_session_path, {:method => :delete, class: "cute-p"} %>
    </td>
  </tr>
</table>







<%= yield %>
<h6> page footer </h6>
</body>
</html>

app/views/lobbies/index.html.erb

<!-- [s567] scratch paper for page -->
<!--
<h1> Lobby: <%= @lobby.name %> </h1>
<h6> Lobby hash: </h6><%= @lobby.as_json %>
<h6> Teacher who created the lobby: </h6><%= @lobby.teacher.as_json %>
<h6> Students inside the lobby: </h6><%= @lobby.students.as_json %>
<h6> What game is being played inside this lobby: </h6><%= @lobby.game.as_json %>
<h6> What teams are playing inside this lobby: </h6><%= @lobby.teams.as_json %>
-->
<!-- <input type="button" value="PLAY"  onclick="playGlass()"> -->
<!-- [/s567] scratch paper for page -->


<!-- [axmr] list of audio needed for this page, uncomment to play sound -->
<!-- <audio id="openingTheme" src="/assets/glass.mp3" ></audio> -->
<!-- [/axmr] list of audio needed for this page -->

<!-- List all lobbies -->

<!-- load the stylesheetsandscripts -->
<% content_for :stylesheetsandscripts do %>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="cssgrids/normalize.css" />
	<link rel="stylesheet" type="text/css" href="cssgrids/demo.css" />
	<link rel="stylesheet" type="text/css" href="cssgrids/component.css" />
	<script src="jsgrids/snap.svg-min.js"></script>
<% end %>

<center><p class="cute-header"> active lobbies </p></center>

<section id="grid" class="grid clearfix">
	<% Lobby.all.each do |l| %>
		<%= link_to inlobby_lobbies_path(controller: "lobbies", action: "inlobby", game_id: l.game_id, lobby_id: l.id), {method: :post, data_path_hover: "m 0,0 0,47.7775 c 24.580441,3.12569 55.897012,-8.199417 90,-8.199417 34.10299,0 65.41956,11.325107 90,8.199417 L 180,0 z"} do %>
				<div>
				<figure>
					<img src="imggrids/<%=rand(1..8)%>.png" />
					<svg viewBox="0 0 180 320" preserveAspectRatio="none"><path d="m 0,0 0,171.14385 c 24.580441,15.47138 55.897012,24.75772 90,24.75772 34.10299,0 65.41956,-9.28634 90,-24.75772 L 180,0 0,0 z"/></svg>
					<figcaption>
						<h2 class="cute-p"><%= l.name %></h2>
						<p>Click on this card to join this lobby. Play a game of <%= l.game.name %> prepared by Professor <%= l.teacher.first_name %></p>
						<!-- <button>View</button> -->
					</figcaption>
				</figure>
				</div>
		 <% end %>
	<% end %>
</section>

<script>
  (function() {

    function init() {
      var speed = 330,
        easing = mina.backout;

      [].slice.call ( document.querySelectorAll( '#grid > a' ) ).forEach( function( el ) {
        var s = Snap( el.querySelector( 'svg' ) ), path = s.select( 'path' ),
          pathConfig = {
            from : path.attr( 'd' ),
            to : el.getAttribute( 'data_path_hover' )
          };

        el.addEventListener( 'mouseenter', function() {
          path.animate( { 'path' : pathConfig.to }, speed, easing );
        } );

        el.addEventListener( 'mouseleave', function() {
          path.animate( { 'path' : pathConfig.from }, speed, easing );
        } );
      } );
    }

    init();

  })();
</script>

LOGGED IN AS: <%= if student_signed_in? then current_student.as_json end%>

app/views/lobbies/ingame.html.erb
<%= hidden_field_tag "student-cookie", current_student.id, { :id => "student-cookie" } %>
<%= hidden_field_tag "student-team", current_student.team_id, { :id => "student-team" } %>

<!-- load the stylesheetsandscripts -->
<% content_for :stylesheetsandscripts do %>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/cssdrag/normalize.css" />
  <link rel="stylesheet" type="text/css" href="/fontsdrag/font-awesome-4.2.0/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="/cssdrag/demo.css" />
  <link rel="stylesheet" type="text/css" href="/cssdrag/bottom-area.css" />
  <script src="/jsdrag/modernizr.custom.js"></script>
  <script src="/jsdrag/draggabilly.pkgd.min.js"></script>
	<script src="/jsdrag/dragdrop.js"></script>
	<!-- for the font -->
	<link rel="stylesheet" type="text/css" href="/cssgrids/demo.css" />
	<!-- for the buttons -->
	<link rel="stylesheet" type="text/css" href="/cssbuttons/normalize.css" />
	<link rel="stylesheet" type="text/css" href="/cssbuttons/vicons-font.css" />
	<link rel="stylesheet" type="text/css" href="/cssbuttons/base.css" />
	<link rel="stylesheet" type="text/css" href="/cssbuttons/buttons.css" />
<% end %>

<!-- Progress Bar -->

<div class="grid clearfix" align="center">
	<table width="100%">
		<tr>
			<td width="10%">
				<font class="sunshine-lcontent"> <%= current_student.first_name %> </font>
			</td>
			<td>
				<div id="myprogressbar" align="center"></div>
			</td>
		</tr>

		<% a = Student.where(lobby_id: current_student.lobby_id).where.not(id: current_student.id).where(team_id: current_student.team_id) %>
		<% a.each do |a| %>
			<tr>
				<td>
					<font class="sunshine-lcontent"> <%= a.first_name %> </font>
				</td>
				<td>
					<div id="<%=a.id.to_s%>" class="teambars" align="center"></div>
				</td>
			</tr>
		<% end %>
	</table>
</div>
<br/>

<div id="grid" class="grid clearfix" align="center" border="1px">
	<div id="questionPane" align="center">
		<font class="cute-question-number">
			question #
			<%=
			Link.where(game_id: @game_to_play).
												where(team_id: current_student.team_id).
												where(player_number: current_student.player_number).
												where(series: @series)[0].series
			%>
		</font>
		<br/>
		<font class="sunshine-qcontent">
		  <%=
		  Question.find(
		  Link.where(game_id: @game_to_play).
		                    where(team_id: current_student.team_id).
		                    where(player_number: current_student.player_number).
		                    where(series: @series)[0].question_id

		  ).content
		  %>
		</font>
	</div>
</div>

<div id="grid" class="grid clearfix" align="center">

		<div class="tutorialPane" align="center" firstdrag="0" firstfull="0" firstsubmit="0">
			<p class="sunshine-tcontent">
				To answer the question<br/>
				drag the colored boxes below to make a combination <br/>
				or scan your objects via NFC
			</p>
		</div>

</div>

<!-- what should be colored boxes -->
<div id="grid" class="grid clearfix" align="center">
					<div class="grid__item" id="green" mycolor="#1ca82f"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="blue"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="red"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="orange"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="black"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="violet"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="torquoise"><i class="fa fa-star-o"></i></div>
					<div class="grid__item" id="pink"><i class="fa fa-star-o"></i></div>

<!--
					<div class="grid__item" hidden ><i class="fa fa-fw fa-image"></i></div>
					<div class="grid__item" hidden ><i class="fa fa-fw fa-image"></i></div>
					<div class="grid__item" hidden ><i class="fa fa-fw fa-image"></i></div>
					<div class="grid__item" hidden ><i class="fa fa-fw fa-image"></i></div>
					<div class="grid__item" hidden ><i class="fa fa-fw fa-image"></i></div>
				-->
</div>

<input type="text" class="answerText" value="" hidden>

<!-- drop area and drop overlay -->
<div id="drop-area" class="drop-area">
  <div>
		<p id="tutorialPane2" class="cute-tooltip">
			Arrange the colors here
		</p>
		<div>
			<input
				type="button"
				class="answerButton"
				value="Submit!"
				series="<%=@series%>"
				game_id="<%=current_student.game_id%>"
				team_id="<%=current_student.team_id%>"
				player_number="<%=current_student.player_number%>"
				hidden
			>
		</div>
    <div class="drop-area__item" id="first" ans="0"></div>
    <div class="drop-area__item" id="second" ans="0"></div>
    <div class="drop-area__item" id="third" ans="0"></div>
    <div class="drop-area__item" id="fourth" ans="0"></div>
  </div>
</div>
<div class="drop-overlay"></div>

<div id="teamprogress">
	<%=
	a = Student.where(lobby_id: current_student.lobby_id).where.not(id: current_student.id)
	a.each do |a|
		a.as_json
	end
	%>
</div>
<div id="allprogress"></div>

LOGGED IN AS: <%= if student_signed_in? then current_student.as_json end%>
GAME: <%= @game_to_play %>
SERIES: <%= @series %>


<!-- Script for my progress bar -->
<script>
	$(function() {

				// highlight the instructions onloac
				$(".tutorialPane").effect("pulsate", 1000);
				$(".tutorialPane").effect("highlight", 1000);

        $("#myprogressbar").progressbar({
                value: 1
        });
				// $("#myprogressbar").css({ 'background': 'green' });
				$("#myprogressbar").height(20);

				// init team bars
				$(".teambars").progressbar({
					value: 1,
				});
				$(".teambars").height(20);
  });
</script>

<!-- Script for NFC Scan -->
<script>
	// upon NFC scan

	function passNFC(tag){
		console.log("NFC!");
		// scan NFC value in the format A,B,C,D and put it in Array
		var array = tag.split(',');
		// concatenate the array and store it in answerText
		nfcans = "";
		for (s of array){
			nfcans += s;
		}
		// alert(nfcans);
		// set this concatenated answer as the new value of answerText
		$(".answerText").val(nfcans);

		$('.drop-area__item').each(function(i, obj) {
			$(this).css("background-color", $("#" + array[i]).css("background-color"));
		});

		// set full to true
		full = true;

		// show dropArea
		var dropArea = document.getElementById( 'drop-area' );
		classie.add( dropArea, 'show' );
		$('.answerButton').show();

	}
</script>

<!-- drag script for color boxes -->
<script>
  (function() {
    var body = document.body,
      dropArea = document.getElementById( 'drop-area' ),
      droppableArr = [], dropAreaTimeout;

		full = false;

		// declare full as false upon onclick to body
		$('.drop-area').click(function() {
			// alert("h");
			if (full){
				full = false;
				classie.remove( dropArea, 'show' );
				$(".answerButton").hide();
			}
		});

		$('.answerButton').click(function(){
			if ($('.tutorialPane').attr("firstsubmit") == "0"){
				$('#tutorialPane2').html("");
				$('.tutorialPane').attr("firstsubmit","1");
			}
		});

    // initialize droppables
    [].slice.call( document.querySelectorAll( '#drop-area .drop-area__item' )).forEach( function( el ) {
      droppableArr.push( new Droppable( el, {
        onDrop : function( instance, draggableEl ) {

          // output the container being dragged on to and the thing being dragged
          console.log(el.id);
          console.log(draggableEl.id);

          // change the color of the receiving drag panel to the color of the box being dragged
          $("#" + el.id).css("background-color", $("#" + draggableEl.id).css("background-color") );
          // change the ans property of the droppables for concatenation
					$("#" + el.id).attr("ans", $("#" + draggableEl.id).attr("id") );

          // generate a concatenated answer
					fans = ""
					$('.drop-area__item').each(function(i, obj) {
    				// console.log($(this).attr("ans"));
						fans += $(this).attr("ans");
					});
					console.log(fans);

					// set this concatenated answer as the new value of answerText
					$(".answerText").val(fans);

          // show checkmark inside the droppabe element
          classie.add( instance.el, 'drop-feedback' );
          clearTimeout( instance.checkmarkTimeout );
          instance.checkmarkTimeout = setTimeout( function() {
            classie.remove( instance.el, 'drop-feedback' );
          }, 800 );
          // ...

					// check if all droppables have been colored
					c = 0
					$('.drop-area__item').each(function(i, obj) {
    				// console.log($(this).attr("ans"));
						if ($(this).attr("ans") == '0'){
							c = c + 1;
						}
					});
					if (c < 1){
						console.log("full");
						full = true
					}

        }
      } ) );
    } );

    // initialize draggable(s)
    [].slice.call(document.querySelectorAll( '#grid .grid__item' )).forEach( function( el ) {
      new Draggable( el, droppableArr, {
        draggabilly : { containment: document.body },
        onStart : function() {
          console.log(el.id);
          $(".answerText").val(el.id);
          // add class 'drag-active' to body
          classie.add( body, 'drag-active' );
          // clear timeout: dropAreaTimeout (toggle drop area)
          clearTimeout( dropAreaTimeout );
          // show dropArea
          classie.add( dropArea, 'show' );

					// change value in tutorial pane
					if ($(".tutorialPane").attr("firstdrag") == "0"){
						// $(".tutorialPane").html("<p></p>");
						$(".tutorialPane").attr("firstdrag", "1");
					}
        },
        onEnd : function( wasDropped ) {
          var afterDropFn = function() {
            // hide dropArea
						if (!full){
            	classie.remove( dropArea, 'show' );
						}
						else{
							$(".answerButton").show();

							// edit tutorial pane during firt full
							if ($(".tutorialPane").attr("firstfull") == "0"){
								$("#tutorialPane2").html("Submit your color code to see if you found the correct object using the button below!<br/> or click anywhere in this yellow area to submit another combination");
								$(".tutorialPane").html("<p></p>");
								$(".tutorialPane").attr("firstfull", "1");
							}
						}
            // remove class 'drag-active' from body
            classie.remove( body, 'drag-active' );
          };

          if( !wasDropped ) {
            afterDropFn();
          }
          else {
            // after some time hide drop area and remove class 'drag-active' from body
            clearTimeout( dropAreaTimeout );
            dropAreaTimeout = setTimeout( afterDropFn, 400 );
          }
        }
      } );
    } );
  })();
</script>

app/views/lobbies/inlobby.html.erb
<!-- <audio id="openingTheme" src="/assets/glass.mp3" ></audio> -->
<%= hidden_field_tag "student-cookie", current_student.id, { :id => "student-cookie" } %>

<!-- load the stylesheetsandscripts -->
<% content_for :stylesheetsandscripts do %>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/cssgrids/normalize.css" />
	<link rel="stylesheet" type="text/css" href="/cssgrids/demo.css" />
	<link rel="stylesheet" type="text/css" href="/cssgrids/component.css" />
	<script src="/jsgrids/snap.svg-min.js"></script>
<% end %>

<center><font class="cute-header"> join a team! </font></center>

<br/>
<% #print join buttons %>
<table width="70%" align="center">
<tr>
	<% for i in 1..@game_to_play.number_of_teams do %>
		<td align="center">
			<font class="cute-p-p"> team <%= i %> </font></br>
			<% for j in 1..@game_to_play.players_per_team do %>
				<input
					type="button"
					value="<%= i.to_s+j.to_s %>"
					class="pickTeamButton"
					id="<%= i.to_s+j.to_s %>"
					i="<%= i.to_s %>"
					j ="<%= j.to_s %>"
				>
				<br/>
			<% end %>
		</td>
	<% end %>
</tr>
</table>

<% #start game button %>
<center>
<%= button_to "Start Game", {controller: "lobbies", action: "ingame", game: "#{@game_to_play.id}"}, {class: "submitLobby", clicked: "0", hidden: true} %>
</center>


GAME BEING PLAYED: <%= @game_to_play.id %>
LOGGED IN AS: <div id="studentAttr">
<%= current_student.as_json %>
</div>

lobby name of student: <%= current_student.lobby.name %>
<script>
(function() {
	/*
	$('.submitLobby').unbind('click').bind('click', function (e) {
		$('.submitLobby').attr("clicked","1");
		e.stopPropagation();
		broadcastSubmitLobbyClick();
	});
	*/

	$(document).keypress(function(e) {
	  if(e.which == 13) {
			console.log("keypress this!");
	    $('.submitLobby').attr("hidden",false);
			broadcastSubmitLobbyClick();
	  }
	});

})();

</script>

app/views/students/index.html.erb
<h1> <%= @student.as_json %> </h1>

app/views/teachers/increategame.html.erb
    <div id="drop-area" hidden>
      <div hidden>
        <div class="drop-area__item" hidden></div>
      </div>
    </div>

<!-- load the stylesheetsandscripts -->
<% content_for :stylesheetsandscripts do %>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/cssdrag/normalize.css" />
  <link rel="stylesheet" type="text/css" href="/fontsdrag/font-awesome-4.2.0/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="/cssdrag/demo.css" />
  <link rel="stylesheet" type="text/css" href="/cssdrag/bottom-area2.css" />
  <script src="/jsdrag/modernizr.custom.js"></script>
  <script src="/jsdrag/draggabilly.pkgd.min.js"></script>
	<script src="/jsdrag/dragdrop.js"></script>

<% end %>

<% for x in @questions do %>
  <%= x.content %>
<% end %>

<br/>
<input type='text' id='gameid' value="<%= Link.maximum(:game_id).next %>" hidden>
<input type='text' id='gamename' placeholder="Name your game">
<input type='text' id='teams' value='3'>
<input type='text' id='ppteam' value='3'>
<input type='text' id='questions' value='3'>
<input type='text' id='search' placeholder="search">
<input type='button' class='generateButton' id='generateButton' value="generate!">
<input type='button' class='saveGameButton' id='saveGameButton' value="Save Game">

<div id="checker">
</div>

<table width="90%" height="600px" align="center">
  <tr>
    <!-- td to hold graphs -->
    <td width="80%" bgcolor="#01FF0000" valign="top">
      <div id="generationPane">
      </div>
    </td>
    <!-- td to hold questions -->
    <td width="20%" bgcolor="#FFFF00" valign="top">
      <table id="searchtable" border="1px">
        <!-- <div id="grid"> -->
          <% for x in @questions do %>
            <tr>
              <td>
                <div id="grid">
                <div class="grid__item" qid="<%=x.id%>" title="<%=x.content%>" content="<%=x.content%>" > <%= x.content[0..50].gsub(/\s\w+\s*$/, '...') %> </div>
                </div>
              </td>
            </tr>
          <% end %>
        <!-- </div> -->
      </table>
    </td>
  </tr>
</table>

<!--
<div id="drop-area">
	<div>
		<div class="drop-area__item"><div class="dummy"></div></div>
	</div>
</div>
    <div id="grid">
    	<div class="grid__item"><i class="fa fa-fw fa-image"></i> This is a sample question </div>
    </div>
<div class="drop-overlay"></div>
-->

<script>
  (function() {
    $.getScript("/jsdrag/dynamic.js")
  })();
</script>

app/views/teachers/increatelobby.html.erb
<%= @xx %>

app/views/teachers/index.html.erb
<h1> Teacher: <%= @teacher.first_name.as_json %> </h1>
<h6> Students created by the teacher </h6> <%= @teacher.students.as_json %> <br/>
<h6> Lobbies created by the teacher </h6> <%= @teacher.lobbies.as_json %> <br/>
<h6> Games being played by the lobbies created by the teacher </h6> <%= @teacher.games.as_json %> <br/>

<%= button_to "creategame", increategame_teachers_path %>
<%= button_to "createlobby", increatelobby_teachers_path %>